// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZIOPUs6qtE7fbzPsUin_n56SqaoD4lSU',
    appId: '1:712122416665:web:a0cacdbfc2573dded4b488',
    messagingSenderId: '712122416665',
    projectId: 'expensetracker-72f70',
    authDomain: 'expensetracker-72f70.firebaseapp.com',
    storageBucket: 'expensetracker-72f70.appspot.com',
    measurementId: 'G-1HNFS5R3EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCabkG_Z-Mva8yq4xeDlmBW13JgpwgtgYg',
    appId: '1:712122416665:android:f3008a590da03540d4b488',
    messagingSenderId: '712122416665',
    projectId: 'expensetracker-72f70',
    storageBucket: 'expensetracker-72f70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiivEiHv37OJxY0yjDZRFpI5T0ywVoFCg',
    appId: '1:712122416665:ios:f1558c754b7251abd4b488',
    messagingSenderId: '712122416665',
    projectId: 'expensetracker-72f70',
    storageBucket: 'expensetracker-72f70.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiivEiHv37OJxY0yjDZRFpI5T0ywVoFCg',
    appId: '1:712122416665:ios:f1558c754b7251abd4b488',
    messagingSenderId: '712122416665',
    projectId: 'expensetracker-72f70',
    storageBucket: 'expensetracker-72f70.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZIOPUs6qtE7fbzPsUin_n56SqaoD4lSU',
    appId: '1:712122416665:web:88aedca66ec36741d4b488',
    messagingSenderId: '712122416665',
    projectId: 'expensetracker-72f70',
    authDomain: 'expensetracker-72f70.firebaseapp.com',
    storageBucket: 'expensetracker-72f70.appspot.com',
    measurementId: 'G-GTNVYRDFJH',
  );
}
